version: "3"
services:
  db:
    container_name: flugdb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flug
      - MYSQL_USER=tuc
      - MYSQL_PASSWORD=tuc
    volumes:
      - "./data/flugdb/data:/var/lib/mysql"
      - "./dumps:/docker-entrypoint-initdb.d"
    expose:
      - 3306
    ports:
      - 3306:3306